config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  
  resources :users, param: :email, shallow: true do
    resources :messages
  end
  
  

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :messages
  # converts the parameters passed in urls from id's to email addresses
  def to_param
    email
  end
  
  #extracts the email without the '.com' from the user
  def self.getEmail(user)
    emailString = user.email
    if !(defined?(emailString)).nil?
      emailString.gsub!('.', '_')
      emailString[0, emailString.length - 4] 
    end
  end
  def self.find_user_by_id(id)
    user = self.find(id)
  end
  # finds user by their extracted email address 
  def self.findUser(inputEmail)
    email = inputEmail.gsub('_', '.')
    item = self.find_by(email: email+".com")
    if !item.nil?
      item
    end
  end
  def self.get_email_by_id(id)
    user = self.find_user_by_id(id)
    self.getEmail(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :set_form, only: [:new, :edit]
  
  # GET /messages
  # GET /messages.json
  def index
    
    # puts "                  begin               "
    # puts User.findUser(params[:user_email]).inspect #Message.where(reciever: params[:user_id])
    # puts "                  end               "
    
    @messages = Message.where(reciever: User.findUser(params[:user_email]).id)
  end
  
  # GET /messages/new
  def new
    @message = Message.new
  end
  
  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    
    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully sent.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end
  
  
  # GET /messages/1
  # GET /messages/1.json
  def show
    puts "                  begin               "
    # puts User.findUser("how_man@mail").inspect #User.getEmail User.find_user_by_id @message.reciever
    # puts User.getEmail User.find_user_by_id(@message.reciever)#.inspect 
    #User.findUser(params[:email]) #user_messages_path(@message.reciever)
    puts "                  end               "
  end
  
  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(user_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  
  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_message
    @message = Message.find(params[:id])
  end
  
  # Callback to set up all the form objects
  def set_form
    # find the maximum number of users possible
    @max_count = User.all.count
    # check if a message already exists
    if !(defined?(@message)).nil?
      @sender = @message.sender
      @reciever = @message.reciever
    else # else the message is then being created
      # set the sender as the user creating the message
      @sender = params[:user_id]
      # let user determine the reciever of his message
      @reciever = nil
    end
    
  end
    
  # Never trust parameters from the scary internet, only allow the white list through.
  def message_params
    params[:message].permit(:sender,:reciever,:content)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    # puts "                  begin               "
    # puts "user path"
    # puts User.getEmail(@users[2]) #user_path(@users[2])
    # puts "                  end               "
  end

  # GET /users/1
  # GET /users/1.json
  def show
    # puts "                  begin               "
    # # puts "new message"
    # puts user_messages_path(@message.reciever)# User.findUser(params[:email]) #new_user_message_path(2)
    # puts "                  end               "
    @messages = Message.where(reciever: @user.id)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    # puts "                  begin               "
    # puts params
    # puts "                  end               "
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      # @user = User.find(params[:id])
      @user = User.findUser(params[:email])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user].permit(:firstName,:lastName,:phone,:email)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  
  def self.add_param(_parameters)
    strBuilder = "?"
    _parameters.each_with_index do |_param,index|
      strBuilder+= "param"+ (index+1).to_s + "=" + _param.to_s + "&"
    end
    strBuilder
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mail | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message, url: @form_path) do |f| %>
  <p><%= "here" %></p>
  <p><%= @form_path %></p>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <label>Sender</label><%= f.number_field(:sender,value: @sender, in: 1..@max_count, step: 1) %><br>
  <label>Reciever</label><%= f.number_field(:reciever,value: @reciever, in: 1..@max_count, step: 1) %><br>
  <label>Content</label><%= f.text_area :content %><br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', user_messages_path(@message.reciever) %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Messages for User</h1>

<table>
  <thead>
    <tr>
      <th>Sender</th>
      <th>Reciever</th>
      <th>Content</th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.sender %></td>
        <td><%= message.reciever %></td>
        <td><%= message.content %></td>
        <td><%= link_to 'Show', message %> <%= link_to 'Edit', edit_message_path(message) %> 
        <%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_user_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', user_messages_path(params[:user_id]) %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Sender</th>
      <th>Reciever</th>
      <th>Content</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @message.sender %></td>
        <td><%= @message.reciever %></td>
        <td><%= @message.content %></td>
      
      </tr>
  </tbody>
</table>


<%= link_to 'Edit', edit_message_path(@message) %> | 
<%= link_to 'Back', user_messages_path(User.get_email_by_id @message.reciever) %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <label>First Name</label><%= f.text_field :firstName %><br>
  <label>Last Name</label><%= f.text_field :lastName %><br>
  <label>Email</label><%= f.text_field :email %><br>
  <label>Phone</label><%= f.text_field :phone %><br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<% provide(:title, "The Title") %>
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Options</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.firstName %></td>
        <td><%= user.lastName %></td>
        <td><%= user.phone %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user_path(User.getEmail user) %> <%= link_to 'Edit', edit_user_path(user) %> 
        <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Options</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @user.firstName %></td>
        <td><%= @user.lastName %></td>
        <td><%= @user.phone %></td>
        <td><%= @user.email %></td>
        <td><%= link_to 'Edit', edit_user_path(@user) %> 
        <%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.sender %></td>
        <td><%= message.reciever %></td>
        <td><%= message.content %></td>
        <td><%= link_to 'Show', message %> <%= link_to 'Edit', edit_message_path(message) %> 
        <%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%=  link_to 'New Message', new_user_message_path(2)
%>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>